{% set name = "invert4geom" %}
{% set version = "0.12.0" %}
{% set python_min = python_min|default("3.9") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/invert4geom-{{ version }}.tar.gz
  sha256: ae3759f069543597ba02d9f68d94404fa1e0fc42c2c05b9914448146fc9d98dc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - xarray
    - verde
    - rioxarray
    - pykdtree
    - xrft
    - harmonica >=0.7
    - polartoolkit
    - numba
    - scipy
    - numba-progress
    - tqdm
    - pygmt
    - dask-core
    - deprecation
    - pooch
    - scikit-learn
    - optuna >=3.6.0
    - torch
    - joblib
    - psutil
    - pyvista
    - trame
    - ipywidgets
    - matplotlib-base
    - seaborn
    - ipython
    - plotly
    - uqpy >=4.1.7
test:
  imports:
    - invert4geom

about:
  home: https://invert4geom.readthedocs.io
  summary: Constrained gravity inversion to recover the geometry of a density contrast.
  license: MIT
  license_file: LICENSE
  doc_url: https://invert4geom.readthedocs.io
  dev_url: https://github.com/mdtanker/invert4geom

extra:
  recipe-maintainers:
    - mdtanker
