{% set name = "invert4geom" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/invert4geom-{{ version }}.tar.gz
  sha256: 0c20f951b12e262b4218b9e0d14c88dc013f23f25e55c2564500d9f68f070ce6

build:
  skip: True  # [py<311]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python
    # Required dependencies
    - numpy >=1.25.0
    - pandas >=2.0.0
    - xarray >=2023.4.0
    - scipy >=1.11.0
    - scikit-learn >=1.3.0,<1.8.0
    - verde
    - boule
    - pooch
    - rioxarray
    - tqdm
    - pygmt
    - harmonica >=0.7
    - deprecation
    - pykdtree
    - xrft
    - polartoolkit >=1.5.0
    - numba
    - numba-progress
    - dask
    # optimization
    - optuna >=4.0 
    - pytorch 
    - joblib
    - psutil
    # visualization
    - pyvista
    - trame
    - ipywidgets
    - matplotlib >=3.7.0
    - seaborn
    - ipython >=8.13.0
    - plotly
test:
  imports:
    - invert4geom

about:
  home: https://invert4geom.readthedocs.io
  summary: Constrained gravity inversion to recover the geometry of a density contrast.
  license: MIT
  license_file: LICENSE
  doc_url: https://invert4geom.readthedocs.io
  dev_url: https://github.com/mdtanker/invert4geom

extra:
  recipe-maintainers:
    - mdtanker
