{% set name = "invert4geom" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/invert4geom-{{ version }}.tar.gz
  sha256: 9b09cdeda636cb81380c7c3b63c7e62b20bbc070e138a1de49f9d5cbcc6a0a41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64
    - pip
  run:
    - python >=3.9
    - numpy
    - pandas
    - xarray
    - verde >=1.8.0
    - rioxarray
    - pykdtree
    - xrft >=1.0
    - harmonica >=0.6.0
    - polartoolkit
    - numba
    - scipy
    - numba-progress
    - tqdm
    - pygmt
    - dask-core
    - deprecation
    - nptyping
    - optuna >=3.1.0
    - optuna-integration
    - botorch >=0.4.0
    - joblib
    - psutil
    - pyvista
    - trame
    - ipywidgets
    - matplotlib-base
    - seaborn
    - ipython
    - plotly
    - uqpy
test:
  imports:
    - invert4geom

about:
  home: https://invert4geom.readthedocs.io
  summary: Constrained gravity inversion to recover the geometry of a density contrast.
  license: MIT
  license_file: LICENSE
  doc_url: https://invert4geom.readthedocs.io
  dev_url: https://github.com/mdtanker/invert4geom

extra:
  recipe-maintainers:
    - mdtanker
