{% set name = "invert4geom" %}
{% set version = "1.1.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/invert4geom-{{ version }}.tar.gz
  sha256: b108c4be92b265136ba7dd00511ef6020ed1d4e170567c95a75307978c820c0f

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    # Required dependencies
    - numpy >=1.25.0
    - pandas >=2.0.0
    - xarray >=2023.4.0
    - scipy >=1.11.0
    - scikit-learn >=1.3.0
    - verde
    - pooch
    - rioxarray
    - tqdm
    - pygmt
    - harmonica >=0.7
    - deprecation
    - pykdtree
    - xrft
    - polartoolkit
    - numba
    - numba-progress
    - dask
    # optimization
    - optuna >=4.0 
    - pytorch 
    - nomkl # [unix]
    - joblib
    - psutil
    # visualization
    - pyvista
    - trame
    - ipywidgets
    - matplotlib
    - seaborn
    - ipython
    - plotly
test:
  imports:
    - invert4geom

about:
  home: https://invert4geom.readthedocs.io
  summary: Constrained gravity inversion to recover the geometry of a density contrast.
  license: MIT
  license_file: LICENSE
  doc_url: https://invert4geom.readthedocs.io
  dev_url: https://github.com/mdtanker/invert4geom

extra:
  recipe-maintainers:
    - mdtanker
